/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartiks.ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KARTIK NIGHANIA
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form user_history
     */
    public bill() {
        initComponents();
        info.getColumnModel().getColumn(0).setPreferredWidth(1);
        info.getColumnModel().getColumn(1).setPreferredWidth(150);
        info.getColumnModel().getColumn(2).setPreferredWidth(5);
        info.getColumnModel().getColumn(3).setPreferredWidth(4);
        info.getColumnModel().getColumn(4).setPreferredWidth(33);
        info.getColumnModel().getColumn(5).setPreferredWidth(9);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        sp = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NUMBER OF ORDERS TO BE PAID:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 255, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("TO BE DELETED");
        jLabel25.setOpaque(true);
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/images.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 80, 80));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 255, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("PRINT ORDER");
        jLabel27.setOpaque(true);
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 160, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TOTAL AMOUNT:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 255, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("PLACE AND");
        jLabel26.setOpaque(true);
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 30));

        total.setBackground(new java.awt.Color(0, 0, 0));
        total.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 51));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        total.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        total.setOpaque(true);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 110, 40));

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        date.setOpaque(true);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 40));

        no.setBackground(new java.awt.Color(0, 0, 0));
        no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no.setOpaque(true);
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, 30));

        info.setBackground(new java.awt.Color(0, 0, 0));
        info.setForeground(new java.awt.Color(51, 255, 51));
        info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ONO", "ITEM", "AMT", "NOS", "DATE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        info.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        info.setFocusTraversalPolicyProvider(true);
        info.setSelectionBackground(new java.awt.Color(255, 255, 255));
        info.setSelectionForeground(new java.awt.Color(0, 0, 0));
        info.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(info);
        info.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 540, 200));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cancel button.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 60, 60));

        sp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        sp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 3, true));
        getContentPane().add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 30));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 255, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ENTER ORDER NO.");
        jLabel24.setOpaque(true);
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 220, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled~1.jpg"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, 90));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, 50));

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 360, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/800px-HK_CWB_Windsor_House_Paul_Lafayet_Bakery_shop_cake_food_counter_May-2012.JPG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        refresh.setBorder(null);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void add_records_in_table(){
    try{
            Class.forName("java.sql.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();

String count_of_records="select count(*) as count from orders where logged_in='online' and status='unpaid';";
String orders="select * from orders where logged_in='online' and status='unpaid';";

ResultSet rs=stmt1.executeQuery(count_of_records);
while(rs.next()){
    int number=Integer.parseInt(rs.getString("count"));
no.setText(""+ number);
  
        
        /*To remove all rows from table*/
  DefaultTableModel tables1=  (DefaultTableModel)info.getModel() ;
        int count=info.getRowCount();
  int m;
  
  for(m=count; m>0; m--){
      tables1.removeRow(0);
      }
  info.setModel(tables1);
 rs=stmt.executeQuery(orders);
   int i;
   int sum=0;
for(i=number;i>=0;i--){
while(rs.next()){
      int sno=Integer.parseInt(rs.getString("sno"));
    String item_ordered=rs.getString("item_ordered");
     double amount=Double.parseDouble(rs.getString("amount"));
     double quantity=Double.parseDouble(rs.getString("quantity"));
       String date_ordered=rs.getString("date_ordered");
     
       double total= (amount*quantity);
    
    DefaultTableModel tables=(DefaultTableModel)info.getModel();
   Object [] names_found={sno, item_ordered, amount, quantity, date_ordered,total};
    tables.addRow(names_found);
    sum += total;
    }
total.setText(""+sum+"/-");
}




}
    }

catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
 }

}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new main_menu().setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 Calendar c=Calendar.getInstance();
date.setText("" +c.getTime()); 
add_records_in_table();

    }//GEN-LAST:event_formWindowGainedFocus

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

    }//GEN-LAST:event_infoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int order_no=(Integer)(sp.getValue());
       try {
                Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
 String delete_records_from_orders="delete from orders where sno ="+ order_no +";";
 Statement stmt1=con.createStatement();
 stmt1.executeUpdate(delete_records_from_orders);
       refresh.doClick();
            }
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
add_records_in_table();        
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  int confirm=JOptionPane.showConfirmDialog(null, "ORDER ONCE PLACED CANNOT BE CANCELLED. ARE YOU SURE.");
  if(confirm==0){
   try {
                
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
                Statement stmt=con.createStatement();
            String update_orders= "update orders set status='paid' where logged_in = 'online';";
               stmt.executeUpdate(update_orders);
              
              new user_dashboard().setVisible(true);
               JOptionPane.showMessageDialog(null, "YOUR ORDER HAVE BEEN PLACED. PLEASE COLLECT YOUR MEAL AT THE COUNTER AND PAY THE MONEY. THANKYOU. ");
                dispose();
      }
   catch(Exception e){
       JOptionPane.showMessageDialog(null,e.getMessage());
   }
  }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTable info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel no;
    private javax.swing.JButton refresh;
    private javax.swing.JSpinner sp;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
