/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartiks.ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author KARTIK NIGHANIA
 */
public class Extras extends javax.swing.JFrame {

    /**
     * Creates new form menu_local_subs
     */
    public Extras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thanksMsg = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        spinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        doneBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        priceLb = new javax.swing.JLabel();

        thanksMsg.setMinimumSize(new java.awt.Dimension(400, 500));
        thanksMsg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("you can cancel or change your preference for any");
        jLabel4.setOpaque(true);
        thanksMsg.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Your order have been placed successfully!");
        jLabel3.setOpaque(true);
        thanksMsg.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("order when you will be shown the bill.");
        jLabel5.setOpaque(true);
        thanksMsg.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/back button.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        thanksMsg.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 180, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/thank-you005.gif"))); // NOI18N
        thanksMsg.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 310));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("you can cancel or change your preference for any order");
        jLabel6.setOpaque(true);
        thanksMsg.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/2.JPG"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 320, 180));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/crisps.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 190, 150));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/1.JPG"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 300, 180));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/drink.jpg"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/NEXT button (2).jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 180, 90));

        spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 50, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("STEPS-\n* SELECT UR MEAL\n*ADD DESIRED QUANTIY\n*PRESS DONE");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 190, 80));

        doneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/done button.jpg"))); // NOI18N
        doneBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });
        getContentPane().add(doneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 90, 40));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cancel-button-similar to done.jpg"))); // NOI18N
        cancelBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 90, 40));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 255, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TO MAIN MENU");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/colorful-background-21.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        priceLb.setText("jLabel6");
        getContentPane().add(priceLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     new main_menu().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 spinner.setEnabled(true);
 doneBtn.setEnabled(true);
 cancelBtn.setEnabled(true);
 jButton2.setEnabled(false);
 jButton3.setEnabled(false);
 jButton4.setEnabled(false);
       
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       spinner.setEnabled(false);
       doneBtn.setEnabled(false);
       cancelBtn.setEnabled(false);
    }//GEN-LAST:event_formWindowGainedFocus

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
int quantity=(Integer)spinner.getValue();
try {
            Class.forName("java.sql.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
String query="select ID from members where status='online';";
String query2="select name from members where status='online';";
 String sno_query="select sno from orders order by sno desc;";
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery(query);
      while(rs.next()){
  int ID_mysql=Integer.parseInt(rs.getString("ID"));
  
  Statement stmt1=con.createStatement();
  rs=stmt1.executeQuery(query2);
  while(rs.next()){
  String name_mysql=rs.getString("name");
    
  Statement stmt3=con.createStatement();
  rs=stmt3.executeQuery(sno_query);
    while(rs.next()){
  int sno=Integer.parseInt(rs.getString("sno"));
    
    String item="";
    int price;
    if(jButton1.isEnabled()){
   item="Double chocolate cookie";
 price=20;
  priceLb.setText(""+price);
    }
    else if(jButton2.isEnabled()){
       item="Chips";
      price=10;
      priceLb.setText(""+price);
    }
    else if(jButton3.isEnabled()){
        item=" Single Chocolate Cookie";
      price=15;
      priceLb.setText(""+price);
    }
    else if(jButton4.isEnabled()){
        item="Coke";
  price=30;
  priceLb.setText(""+price);
    }
    Calendar c=Calendar.getInstance();
   int price_final= Integer.parseInt(priceLb.getText());
    String order="insert into orders values("+(sno+1)+","+ID_mysql+",'online','"+name_mysql+"','"+item+"',"+Integer.parseInt(priceLb.getText())+","+quantity+",'"+(c.get(Calendar.YEAR))+"-"+(c.get(Calendar.MONTH)+1)+"-"+(c.get(Calendar.DATE))+"','unpaid');" ;
    Statement stmt4=con.createStatement();
    stmt4.executeUpdate(order);
    
   String total_collection= "update total_collection set total_money = ( total_money + " + price_final*quantity + ") , total_orders = total_orders +1  ;";
   String new_order_placed_today ="insert into total_collection_perday values ('order placed','"+(c.get(Calendar.YEAR))+"-"+(c.get(Calendar.MONTH)+1)+"-"+(c.get(Calendar.DATE))+"',"+price_final*quantity+");";
   
   Statement stmt5=con.createStatement();
   Statement stmt6=con.createStatement();
   stmt5.executeUpdate(total_collection);
    stmt6.executeUpdate(new_order_placed_today);
  }  
  }
      }
    
   jButton1.setEnabled(true);
 jButton2.setEnabled(true);
jButton3.setEnabled(true);
jButton4.setEnabled(true);
 spinner.setEnabled(false);
 cancelBtn.setEnabled(false);
  doneBtn.setEnabled(false);
 thanksMsg.setVisible(true);
 dispose();
}
catch(Exception e){

jButton1.setEnabled(true);
 jButton2.setEnabled(true);
jButton3.setEnabled(true);
jButton4.setEnabled(true);
 spinner.setEnabled(false);
 cancelBtn.setEnabled(false);
  doneBtn.setEnabled(false);
 thanksMsg.setVisible(true);
 dispose();

}
    

    }//GEN-LAST:event_doneBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
   jButton1.setEnabled(true);
   jButton2.setEnabled(true);
   jButton3.setEnabled(true);
   jButton4.setEnabled(true);
   doneBtn.setEnabled(false);
   spinner.setEnabled(false);
   cancelBtn.setEnabled(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add you spinner.setEnabled(true);
 spinner.setEnabled(true);
        doneBtn.setEnabled(true);
 cancelBtn.setEnabled(true);
 jButton2.setEnabled(false);
 jButton1.setEnabled(false);
 jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  spinner.setEnabled(true);
 doneBtn.setEnabled(true);
 cancelBtn.setEnabled(true);
 jButton1.setEnabled(false);
 jButton3.setEnabled(false);
 jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 spinner.setEnabled(true);
 doneBtn.setEnabled(true);
 cancelBtn.setEnabled(true);
  jButton2.setEnabled(false);;
 jButton3.setEnabled(false);
 jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered

    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
 
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
    
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
    
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
  
  
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited

    }//GEN-LAST:event_jButton3MouseExited

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
  
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited

    }//GEN-LAST:event_jButton4MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        thanksMsg.setVisible(false);
        new Extras().setVisible(true);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel priceLb;
    private javax.swing.JSpinner spinner;
    private javax.swing.JDialog thanksMsg;
    // End of variables declaration//GEN-END:variables
}
