/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartiks.ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;

/**
 *
 * @author KARTIK NIGHANIA
 */
public class owners_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form owners_dashboard
     */
    public owners_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        tot_no = new javax.swing.JLabel();
        tot_amt = new javax.swing.JLabel();
        grand_total = new javax.swing.JLabel();
        no_of_order = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tot_orders = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datelb = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernameLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TODAY'S TRANSACTIONS");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 230, -1));

        tot_no.setBackground(new java.awt.Color(0, 0, 0));
        tot_no.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tot_no.setForeground(new java.awt.Color(255, 255, 255));
        tot_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot_no.setOpaque(true);
        getContentPane().add(tot_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, 30));

        tot_amt.setBackground(new java.awt.Color(0, 0, 0));
        tot_amt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tot_amt.setForeground(new java.awt.Color(255, 255, 255));
        tot_amt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot_amt.setOpaque(true);
        getContentPane().add(tot_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 160, 30));

        grand_total.setBackground(new java.awt.Color(0, 0, 0));
        grand_total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        grand_total.setForeground(new java.awt.Color(255, 255, 255));
        grand_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grand_total.setOpaque(true);
        getContentPane().add(grand_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 140, 30));

        no_of_order.setBackground(new java.awt.Color(0, 0, 0));
        no_of_order.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        no_of_order.setForeground(new java.awt.Color(255, 255, 255));
        no_of_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_of_order.setOpaque(true);
        getContentPane().add(no_of_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 160, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/thumbs up~1.jpg"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 205, 100, -1));

        tot_orders.setBackground(new java.awt.Color(0, 0, 0));
        tot_orders.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tot_orders.setForeground(new java.awt.Color(255, 255, 255));
        tot_orders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot_orders.setOpaque(true);
        getContentPane().add(tot_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 140, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/MONEY COLLECTION.jpg"))); // NOI18N
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 60));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TOTAL ORDERS PLACED :");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 260, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TODAYS COLLECTION :");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 330, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 255, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TOTAL NUMBER OF MEMBERS :");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 330, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("GRAND TOTAL COLLECTION :");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 260, -1));

        datelb.setBackground(new java.awt.Color(0, 0, 0));
        datelb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelb.setForeground(new java.awt.Color(255, 255, 255));
        datelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datelb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        datelb.setOpaque(true);
        getContentPane().add(datelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 240, 50));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PROFILE");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 90, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ALL DETAILS OF OUR MEMBERS.");
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 280, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TOTAL NUMBER OF ORDERS PLACED TILL NOW");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 410, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("NUMBER OF ORDERS PLACED TODAY :");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 330, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CLICK HERE TO GET");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 170, -1));

        id.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        id.setForeground(new java.awt.Color(204, 0, 0));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("ID : 101");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/edit.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 70, 100));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EDIT USER'S");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGOUT.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/welcome1.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 370, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/b.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 110, 90));

        usernameLb.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        usernameLb.setForeground(new java.awt.Color(255, 255, 0));
        usernameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 70));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 740, 180));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 510, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/animated_background_2_by_greyannis-d5c8gj0.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new Owners_user__search().setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 Calendar c=Calendar.getInstance();

datelb.setText(" " +c.getTime());
        try {
            Class.forName("java.sql.Driver");
       
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();
Statement stmt2=con.createStatement();
Statement stmt3=con.createStatement();

String username= "Select name from members where ID=101;";
String present_members= "Select count(*) as number from members;";
String total_transaction="SELECT total_orders , total_money FROM total_collection ;";
String transaction_done_today="SELECT COUNT(*) as recent_count, sum(amount) as recent_total  FROM total_collection_perday WHERE date='"+(c.get(Calendar.YEAR))+"-"+(c.get(Calendar.MONTH)+1)+"-"+(c.get(Calendar.DATE))+"' ;";

ResultSet rs=stmt.executeQuery(present_members);
while(rs.next()){
   tot_no.setText(rs.getString("number"));
   
  rs=stmt1.executeQuery(total_transaction);
while(rs.next()){
   tot_orders.setText(rs.getString("total_orders"));
   grand_total.setText(rs.getString("total_money"));
  
       rs=stmt2.executeQuery(transaction_done_today);
       while(rs.next()){
           no_of_order.setText(rs.getString("recent_count"));
           tot_amt.setText(rs.getString("recent_total"));
           
          rs=stmt3.executeQuery(username);
          while(rs.next()){
              usernameLb.setText(rs.getString("name"));
          }
       }
}
}
        }
 catch(Exception e){
     
 }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new LOGIN_FORM().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new edit_owners_profile().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(owners_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(owners_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(owners_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(owners_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new owners_dashboard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelb;
    private javax.swing.JLabel grand_total;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel no_of_order;
    private javax.swing.JLabel tot_amt;
    private javax.swing.JLabel tot_no;
    private javax.swing.JLabel tot_orders;
    private javax.swing.JLabel usernameLb;
    // End of variables declaration//GEN-END:variables
}
