/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kartiks.ip.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KARTIK NIGHANIA
 */
public class user_history extends javax.swing.JFrame {

    /**
     * Creates new form user_history
     */
    public user_history() {
        initComponents();
      
        info.getColumnModel().getColumn(0).setPreferredWidth(150);
        info.getColumnModel().getColumn(1).setPreferredWidth(5);
        info.getColumnModel().getColumn(2).setPreferredWidth(4);
        info.getColumnModel().getColumn(3).setPreferredWidth(33);
        info.getColumnModel().getColumn(4).setPreferredWidth(9);
        info.getColumnModel().getColumn(5).setPreferredWidth(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NUMBER OF ORDERS PLACED:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TOTAL AMOUNT OF TRANSACTIONS MADE:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        total.setBackground(new java.awt.Color(0, 0, 0));
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        total.setOpaque(true);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 70, 30));

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        date.setOpaque(true);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 250, 40));

        no.setBackground(new java.awt.Color(0, 0, 0));
        no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no.setOpaque(true);
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 30));

        info.setBackground(new java.awt.Color(0, 0, 0));
        info.setForeground(new java.awt.Color(51, 255, 51));
        info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM                            .", "AMT", "NOS", "DATE", "STATUS", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        info.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        info.setFocusTraversalPolicyProvider(true);
        info.setSelectionBackground(new java.awt.Color(255, 255, 255));
        info.setSelectionForeground(new java.awt.Color(0, 0, 0));
        info.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(info);
        info.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 540, 240));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cancel button.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/history background.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new user_dashboard().setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 Calendar c=Calendar.getInstance();

date.setText("" +c.getTime());  
try{
            Class.forName("java.sql.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/subway","root","123");
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();

String count_of_records="select count(*) as count from orders where logged_in='online';";
String orders="select * from orders where logged_in='online';";

ResultSet rs=stmt1.executeQuery(count_of_records);
while(rs.next()){
    int number=Integer.parseInt(rs.getString("count"));
     if(number==0){
       
      new user_dashboard().setVisible(true);
   JOptionPane.showMessageDialog(null, "YOU HAVE NOT PLACED ANY ORDER YET !"); 
   dispose();
    }
    else{
    rs=stmt.executeQuery(orders);
   int i;
   int sum=0;
for(i=number;i>=0;i--){
while(rs.next()){
     
    String item_ordered=rs.getString("item_ordered");
     double amount=Double.parseDouble(rs.getString("amount"));
     double quantity=Double.parseDouble(rs.getString("quantity"));
       String date_ordered=rs.getString("date_ordered");
        String status=rs.getString("status");
       double total= (amount*quantity);
    
    DefaultTableModel tables=(DefaultTableModel)info.getModel();
   Object [] names_found={item_ordered, amount, quantity, date_ordered, status,total};
    tables.addRow(names_found);
    sum += total;
    }
total.setText(""+sum+"/-");

no.setText(""+ info.getRowCount()); 
    }
}
}
}

catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
 }

    }//GEN-LAST:event_formWindowGainedFocus

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

    }//GEN-LAST:event_infoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_history().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTable info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
